version: '3.5'

services:
  ifr-cpu:
    image: insightface-rest-cpu:${IFR_VERSION}
    build:
      context: ../src
      dockerfile: ../src/Dockerfile_cpu
    hostname: ifr
    env_file:
      - cpu.env
    volumes:
      - ../models:/models
      - ../src/api_trt:/app
    ports:
      - 18081:18080

